### ISSUE TITLE
Move issues to habari/system

### ISSUE THREAD

**Issue by michaeltwofish** [habari/habari#444]
When we moved to github, we decided to put the issues in habari/habari, thinking that would be clearer for people trying to open tickets. The reality is that you have to know your way around github to open issues anyway, so having the issues in habari/habari just confuses people and breaks a lot of the auto-linking goodness that github provides for issues and commits.

We should move issues to habari/system.

**Comment by Konzertheld** [comment]
There is also Issue mover for GitHub, which copies issues to another repo, adds references and closes the original issue. I would like to use that to "move" all the system-related issues to system and plugin-related issues to the according plugin/theme repos. If starting with issue #78 as I did for testing we could preserve most of the numbering, therefore keeping lots of references in commit messages working / making them work. Looks like this: habari/system#78. We would end up with a bunch of issues that are below 78 in habari/habari and above 600-something in habari/system, though. But they would have references.

We really should separate issues for habari, system, plugins and themes. E.g. there is #564 which is not code related and should stay in habari/habari. Copying issues over and closing the old ones would be similar to moving threads in boards, I think that's the best option so far.

**Comment by Konzertheld** [comment]
Further explanation regarding my above post from 2014:

Commit messages like "closes #123" will link to #123 in the system repo. Those will mostly work - for issue numbers 78 to 600-something and issues created after the move. Some will link to pull requests, because 1 to 77 almost all are pull requests, that's why we can't use those numbers in the system repo. We might add links to the real issues to those pull requests.

Commit messages like "closes habari/habari#123" will continue to work and link to a closed issue in the habari repo which has a reference to the issue in the system repo.

Issue comments linking to other issues will continue to work and link to closed issues which have reference to the moved issue in the system repo.

**Comment by Konzertheld** [comment]
It turned out none of the scripts take care of the closed/open status, so I would have to track those manually, which would double the work. As the suggested approach is not perfect, it is not worth the enormous work. Maybe somewhen GitHub introduces a new feature we can't think of now and we move our issues, but for now I only copied over all the plugin and theme issues and closed them here, because they really should be separated. Issues for system and global habari stuff stay here.
